//https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

const greetings = ["hello", "hi", "hey", "greetings", "salutations"];

const randomMessages = ["Learning Skills!", "pro Durham propaganda", "Wow, you're on a merit streak!", "Check your GPA", "<em><br></br></em>","Sign up to Waffle+ today!", "Zscaler Certified!", "Works on Master Combination Locks", "System requirements: Yes","Also try ChatGPT"]

const bbcTrigger = ["bbc", "passcode", "password", "code"]

const classrooms = [
    "sg11", "sg12",
    "library",
    "s421", "s423", "s424", "s425", "s426", "s427", "s436","s440", "s438", "s439",
    "s512", "s538", 
    "s520", "s521", "s522", "s523", "s524",
    "s531", "s532","s533", 
    "s801", "s810", "s815", "s817", 
    "s838", "s839", "s840", "s841", 
    "blg02", "blg03", "blg04", "blg05", "blg06", "blg07", "blg08", 
    "bg18", "bg19", "bg20", 
    "b101", "b102", "b103", "b120", 
    "b125", "b127", "b131", "b132",
    "b201", "b202", "b203", "b204", "b205", "b206", "b207", "b208", "b209",
    "b301", "b302", "b303", "b304", "b305", 
    "b401", "b403", "b404", "b405", "b406", "b407", "b408", "b409", "b410", "b411", "b412", "b413",
    "gym", "fairfax", "gymnasium", "heath", "black", "auditorium", "bbca", "health", "office", "it", "cathedral", "chapter", "bbc_reception", "sah_reception"]

const randomText = document.getElementById('random-message');

let messageOfTheDay = Math.floor(Math.random() * randomMessages.length)
console.log(messageOfTheDay)
randomText.textContent = randomMessages[messageOfTheDay]


const levels =  new Map([
    ["sg11",0],["sg12",0],
    ["library",4],
    ["s421",4], ["s423",4], ["s424",4], ["s425",4], ["s426",4], ["s427",4], ["s436",4],["s440",4], ["s438",4], ["s439",4],
    ["s512", 5], ["s538", 5], 
    ["s520", 5], ["s521", 5], ["s522", 5], ["s523", 5], ["s524", 5],
    ["s531", 5], ["s532", 5],["s533", 5], 
    ["s801", 8], ["s810", 8], ["s815", 8], ["s817", 8], 
    ["s838", 8], ["s839", 8], ["s840", 8], ["s841", 8], 
    ["blg02", -1], ["blg03", -1], ["blg04", -1], ["blg05", -1], ["blg06", -1], ["blg07", -1], ["blg08", -1], 
    ["bg18", 0], ["bg19", 0], ["bg20", 0], 
    ["b101", 1], ["b102", 1], ["b103", 1], ["b120", 1], 
    ["b125", 1], ["b127", 1], ["b131", 1], ["b132", 1],
    ["b201", 2], ["b202", 2], ["b203", 2], ["b204", 2], ["b205", 2], ["b206", 2], ["b207", 2], ["b208", 2], ["b209", 2],
    ["b301", 3], ["b302", 3], ["b303", 3], ["b304", 3], ["b305", 3], 
    ["b401", 4], ["b403", 4], ["b404", 4], ["b405", 4], ["b406", 4], ["b407", 4], ["b408", 4], ["b409", 4], ["b410", 4], ["b411", 4], ["b412", 4], ["b413", 4],
    ["gym", 7], ["fairfax", 8], ["gymnasium", 7], ["heath", 5], ["black", 0], ["auditorium", 0], ["bbca", 0], ["health",6 ], ["office", 6], ["it", 3], ["cathedral", 0], ["chapter", 0], ["bbc_reception",1], ["sah_reception", 0]])

const building =  new Map([
    ["sg11","SAH"],["sg12","SAH"],
    ["library","SAH"],
    ["s421","SAH"], ["s423","SAH"], ["s424","SAH"], ["s425","SAH"], ["s426","SAH"], ["s427","SAH"], ["s436","SAH"],["s440","SAH"], ["s438","SAH"], ["s439","SAH"],
    ["s512","SAH"], ["s538","SAH"], 
    ["s520","SAH"], ["s521","SAH"], ["s522","SAH"], ["s523","SAH"], ["s524","SAH"], 
    ["s531","SAH"], ["s532","SAH"],["s533","SAH"], 
    ["s801","SAH"], ["s810","SAH"], ["s815","SAH"], ["s817","SAH"], 
    ["s838","SAH"], ["s839","SAH"], ["s840","SAH"], ["s841","SAH"], 
    ["blg02","BBC"], ["blg03","BBC"], ["blg04","BBC"], ["blg05","BBC"], ["blg06","BBC"], ["blg07","BBC"], ["blg08","BBC"], 
    ["bg18","BBC"], ["bg19","BBC"], ["bg20","BBC"], 
    ["b101","BBC"], ["b102","BBC"], ["b103","BBC"], ["b120","BBC"], 
    ["b125","BBC"], ["b127","BBC"], ["b131","BBC"], ["b132","BBC"],
    ["b201","BBC"], ["b202","BBC"], ["b203","BBC"], ["b204","BBC"], ["b205","BBC"], ["b206","BBC"], ["b207","BBC"], ["b208","BBC"], ["b209","BBC"],
    ["b301","BBC"], ["b302","BBC"], ["b303","BBC"], ["b304","BBC"], ["b305","BBC"], 
    ["b401","BBC"], ["b403","BBC"], ["b404","BBC"], ["b405","BBC"], ["b406","BBC"], ["b407","BBC"], ["b408","BBC"], ["b409","BBC"], ["b410","BBC"], ["b411","BBC"], ["b412","BBC"], ["b413","BBC"],
    ["gym", "SAH"], ["fairfax", "SAH"], ["gymnasium", "SAH"], ["heath", "SAH"], ["black", "BBC"], ["auditorium", "BBC"], ["bba", "BBC"], ["health","SAH" ], ["office", "SAH"], ["it", "SAH"], ["cathedral", "SAH"], ["chapter", "SAH"], ["bbc_reception", "BBC"], ["sah_reception", "SAH"]])



const standard_origin =  new Map([
    ["sg11","no"],["sg12","no"],
    ["library","yes"],
    ["s421","yes"], ["s423","yes"], ["s424","yes"], ["s425","yes"], ["s426","yes"], ["s427","yes"], ["s436","yes"],["s440","yes"], ["s438","yes"], ["s439","yes"],
    ["s512","yes"], ["s538","yes"], 
    ["s520","yes"], ["s521","yes"], ["s522","yes"], ["s523","yes"], ["s524","yes"],
    ["s531","yes"], ["s532","yes"],["s533","yes"], 
    ["s801","yes"], ["s810","yes"], ["s815","yes"], ["s817","yes"], 
    ["s838","yes"], ["s839","yes"], ["s840","yes"], ["s841","yes"], 
    ["blg02","yes"], ["blg03","yes"], ["blg04","yes"], ["blg05","yes"], ["blg06","yes"], ["blg07","yes"], ["blg08","yes"], 
    ["bg18","yes"], ["bg19","yes"], ["bg20","yes"], 
    ["b101","yes"], ["b102","yes"], ["b103","yes"], ["b120","yes"], 
    ["b125","yes"], ["b127","yes"], ["b131","yes"], ["b132","yes"],
    ["b201","yes"], ["b202","yes"], ["b203","yes"], ["b204","yes"], ["b205","yes"], ["b206","yes"], ["b207","yes"], ["b208","yes"], ["b209","yes"],
    ["b301","yes"], ["b302","yes"], ["b303","yes"], ["b304","yes"], ["b305","yes"], 
    ["b401","yes"], ["b403","yes"], ["b404","yes"], ["b405","yes"], ["b406","yes"], ["b407","yes"], ["b408","yes"], ["b409","yes"], ["b410","yes"], ["b411","yes"], ["b412","yes"], ["b413","yes"],
    ["gym", "yes"], ["fairfax", "yes"], ["gymnasium", "yes"], ["heath", "yes"], ["black", "yes"], ["auditorium", "yes"], ["bbca", "yes"], ["health","yes" ], ["office", "yes"], ["helpdesk", "yes"], ["cathedral", "no"], ["chapter", "no"]])

const from_mid =  new Map([
    ["sg11","walk towards the gym, turn right down the stairs, then turn left"],
    ["sg12","walk towards the gym, turn right down the stairs"],
    ["library","follow sign to Middle School Library"],
    ["s421","follow signs to Middle School Library, then walk through to the left"], 
    ["s423","follow signs to Middle School Library, then turn left before you enter, then turn right and travel to the end of the corridor"], 
    ["s424","follow signs to Middle School Library, then turn left before you enter, then turn right"], 
    ["s425","follow signs to Middle School Library, then turn left before you enter, then turn right"], 
    ["s426","follow signs to Middle School Library, then turn left before you enter"], 
    ["s427","follow signs to the Year 7 Open Area, then turn right as soon as you enter"], 
    ["s436","follow signs to the Year 7 Open Area, then travel forwards and to the right"],
    ["s438","follow signs to the Year 7 Open Area, then turn left after the first corridor"], 
    ["s439","follow signs to the Year 7 Open Area, then turn left after the first corridor"],
    ["s440","follow signs to the Year 7 Open Area, then turn left after the first corridor"],
    ["s512","follow signs to the Heath Centre, then turn left"], 
    ["s538","follow signs to the Heath Centre, then turn right"], 
    ["s520","follow signs to the Year 8 Open Area, then turn right"], 
    ["s521","follow signs to the Year 8 Open Area, then turn right"],
    ["s522","follow signs to the Year 8 Open Area, then continue straight"], 
    ["s523","follow signs to the Year 8 Open Area, then continue straight"], 
    ["s524","follow signs to the Year 8 Open Area, then continue straight"],
    ["s531","follow signs to the Year 8 Open Area, turn left, then turn right at the corridor"], 
    ["s532","follow signs to the Year 8 Open Area, turn left, then turn right at the corridor"],
    ["s533","follow signs to the Year 8 Open Area, turn left, then turn right at the corridor"], 
    ["s801","follow signs to the Fairfax room"], 
    ["s810","follow signs to the Fairfax room"], 
    ["s815","follow signs to the Fairfax room, then turn left down the corridor"], 
    ["s817","follow signs to the Fairfax room, then turn left down the corrdior"], 
    ["s838","follow signs"], 
    ["s839","directions_placeholder_v2"], 
    ["s840","directions_placeholder_v2"], 
    ["s841","directions_placeholder_v2"], 
    ["blg02","directions_placeholder_v2"], 
    ["blg03","directions_placeholder_v2"], 
    ["blg04","directions_placeholder_v2"], 
    ["blg05","directions_placeholder_v2"], 
    ["blg06","directions_placeholder_v2"], 
    ["blg07","directions_placeholder_v2"], 
    ["blg08","directions_placeholder_v2"], 
    ["bg18","directions_placeholder_v2"], 
    ["bg19","directions_placeholder_v2"], 
    ["bg20","directions_placeholder_v2"], 
    ["b101","directions_placeholder_v2"], 
    ["b102","directions_placeholder_v2"], 
    ["b103","directions_placeholder_v2"], 
    ["b120","directions_placeholder_v2"], 
    ["b125","directions_placeholder_v2"], 
    ["b127","directions_placeholder_v2"], 
    ["b131","directions_placeholder_v2"], 
    ["b132","directions_placeholder_v2"],
    ["b201","directions_placeholder_v2"], 
    ["b202","directions_placeholder_v2"],
    ["b203","directions_placeholder_v2"], 
    ["b204","directions_placeholder_v2"], 
    ["b205","directions_placeholder_v2"], 
    ["b206","directions_placeholder_v2"], 
    ["b207","directions_placeholder_v2"], 
    ["b208","directions_placeholder_v2"], 
    ["b209","directions_placeholder_v2"],
    ["b301","directions_placeholder_v2"], 
    ["b302","directions_placeholder_v2"], 
    ["b303","directions_placeholder_v2"], 
    ["b304","directions_placeholder_v2"], 
    ["b305","directions_placeholder_v2"], 
    ["b401","directions_placeholder_v2"], 
    ["b403","directions_placeholder_v2"], 
    ["b404","directions_placeholder_v2"], 
    ["b405","directions_placeholder_v2"], 
    ["b406","directions_placeholder_v2"], 
    ["b407","directions_placeholder_v2"], 
    ["b408","directions_placeholder_v2"], 
    ["b409","directions_placeholder_v2"], 
    ["b410","directions_placeholder_v2"], 
    ["b411","directions_placeholder_v2"], 
    ["b412","directions_placeholder_v2"], 
    ["b413","directions_placeholder_v2"],
    ["gym", "directions_placeholder_v2"], 
    ["fairfax", "directions_placeholder_v2"], 
    ["gymnasium", "directions_placeholder_v2"],
    ["heath", "directions_placeholder_v2"], 
    ["black", "directions_placeholder_v2"], 
    ["auditorium", "directions_placeholder_v2"], 
    ["bbca", "directions_placeholder_v2"], 
    ["health","directions_placeholder_v2" ], 
    ["office", "directions_placeholder_v2"],  
    ["cathedral", "directions_placeholder_v2"], 
    ["chapter", "directions_placeholder_v2"], 
    ["bbc_reception", "directions_placeholder_v2"],
     ["sah_reception", 'SAH Reception is locatated in the foyer on Ground Floor']
    ])


const to_mid =  new Map([
    ["sg11","directions_placeholder"],
    ["sg12","directions_placeholder"],
    ["library","directions_placeholder"],
    ["s421","directions_placeholder"], 
    ["s423","directions_placeholder"], 
    ["s424","directions_placeholder"], 
    ["s425","directions_placeholder"], 
    ["s426","directions_placeholder"], 
    ["s427","directions_placeholder"], 
    ["s436","directions_placeholder"],
    ["s440","directions_placeholder"], 
    ["s438","directions_placeholder"], 
    ["s439","directions_placeholder"],
    ["s512","directions_placeholder"], 
    ["s538","directions_placeholder"], 
    ["s520","directions_placeholder"], 
    ["s521","directions_placeholder"],
    ["s522","directions_placeholder"], 
    ["s523","directions_placeholder"], 
    ["s524","directions_placeholder"],
    ["s531","directions_placeholder"], 
    ["s532","directions_placeholder"],
    ["s533","directions_placeholder"], 
    ["s801","directions_placeholder"], 
    ["s810","directions_placeholder"], 
    ["s815","directions_placeholder"], 
    ["s817","directions_placeholder"], 
    ["s838","directions_placeholder"], 
    ["s839","directions_placeholder"], 
    ["s840","directions_placeholder"], 
    ["s841","directions_placeholder"], 
    ["blg02","directions_placeholder"], 
    ["blg03","directions_placeholder"], 
    ["blg04","directions_placeholder"], 
    ["blg05","directions_placeholder"], 
    ["blg06","directions_placeholder"], 
    ["blg07","directions_placeholder"], 
    ["blg08","directions_placeholder"], 
    ["bg18","directions_placeholder"], 
    ["bg19","directions_placeholder"], 
    ["bg20","directions_placeholder"], 
    ["b101","directions_placeholder"], 
    ["b102","directions_placeholder"], 
    ["b103","directions_placeholder"], 
    ["b120","directions_placeholder"], 
    ["b125","directions_placeholder"], 
    ["b127","directions_placeholder"], 
    ["b131","directions_placeholder"], 
    ["b132","directions_placeholder"],
    ["b201","directions_placeholder"], 
    ["b202","directions_placeholder"],
    ["b203","directions_placeholder"], 
    ["b204","directions_placeholder"], 
    ["b205","directions_placeholder"], 
    ["b206","directions_placeholder"], 
    ["b207","directions_placeholder"], 
    ["b208","directions_placeholder"], 
    ["b209","directions_placeholder"],
    ["b301","directions_placeholder"], 
    ["b302","directions_placeholder"], 
    ["b303","directions_placeholder"], 
    ["b304","directions_placeholder"], 
    ["b305","directions_placeholder"], 
    ["b401","directions_placeholder"], 
    ["b403","directions_placeholder"], 
    ["b404","directions_placeholder"], 
    ["b405","directions_placeholder"], 
    ["b406","directions_placeholder"], 
    ["b407","directions_placeholder"], 
    ["b408","directions_placeholder"], 
    ["b409","directions_placeholder"], 
    ["b410","directions_placeholder"], 
    ["b411","directions_placeholder"], 
    ["b412","directions_placeholder"], 
    ["b413","directions_placeholder"],
    ["gym", "directions_placeholder"], 
    ["fairfax", "directions_placeholder"], 
    ["gymnasium", "directions_placeholder"],
    ["heath", "directions_placeholder"], 
    ["black", "directions_placeholder"], 
    ["auditorium", "directions_placeholder"], 
    ["bbca", "directions_placeholder"], 
    ["health","directions_placeholder" ], 
    ["office", "directions_placeholder"],  
    ["cathedral", "directions_placeholder"], 
    ["chapter", "directions_placeholder"], 
    ["bbc_reception", "directions_placeholder"],
     ["sah_reception", 'directions_placeholder']
    ])



    const sub_area =  new Map([
    ["sg11","sports_centre"], ["sg12","sports_centre"],
    ["library","library_side"],
    ["s421","library_side"], ["s423","library_side"], ["s424","library_side"], ["s425","library_side"], ["s426","library_side"], ["s427","open_side"], ["s436","open_side"],["s440","open_side"], ["s438","open_side"], ["s439","open_side"],
    ["s512","heath_side"], ["s538","heath_side"], 
    ["s520","near_corridor"], ["s521","near_corridor"], ["s522","near_corridor"], ["s523","near_corridor"], ["s524","near_corridor"], 
    ["s531","far_corridor"], ["s532","far_corridor"],["s533","far_corridor"], 
    ["s801","music"], ["s810","music"], ["s815","music"], ["s817","music"], 
    ["s838","science"], ["s839","science"], ["s840","science"], ["s841","science"], 
    ["blg02","design"], ["blg03","design"], ["blg04","design"], ["blg05","design"], ["blg06","design"], ["blg07","design"], ["blg08","design"], 
    ["bg18","far_plaza"], ["bg19","far_plaza"], ["bg20","far_plaza"], 
    ["b101","bbc_science"], ["b102","bbc_science"], ["b103","bbc_science"], ["b120","bbc_science_but_no"], 
    ["b125","bbc_va"], ["b127","bbc_va"], ["b131","bbc_va"], ["b132","bbc_va"],
    ["b201","level_two"], ["b202","level_two"], ["b203","level_two"], ["b204","level_two"], ["b205","level_two"], ["b206","level_two"], ["b207","level_two"], ["b208","level_two"], ["b209","level_two"],
    ["b301","not_library"], ["b302","not_library"], ["b303","not_library"], ["b304","not_library"], ["b305","not_library"], 
    ["b401","bbc_level_four"], ["b403","bbc_level_four"], ["b404","bbc_level_four"], ["b405","bbc_level_four"], ["b406","bbc_level_four"], ["b407","bbc_level_four"], ["b408","bbc_level_four"], ["b409","bbc_level_four"], ["b410","bbc_level_four"], ["b411","bbc_level_four"], ["b412","bbc_level_four"], ["b413","bbc_level_four"],
    ["gym", "level_7"], ["fairfax", "music"], ["gymnasium", "level_7"], ["heath", "heath_side"], ["black", "bbc_foyer_area"], ["auditorium", "bbc_foyer_area"], ["bbca", "bbc_foyer_area"], ["health","junior_school" ], ["office", "year_9"], ["cathedral", "square_outside"], ["chapter", "square_outside"], ["bbc_reception", "bbc_foyer_area"], ["sah_reception", "sah_foyer"]])



    const sub_directions = new Map([
        ["sports_centre###square_outside", "SPORTS CENTRE TO SQUARE OUTSIDE"],
        ["sports_centre###sah_foyer", "SPORTS CENTRE TO SAH FOYER"],
        ["square_outside###sports_centre", "SQUARE OUTSIDE TO SPORTS CENTRE"],
        ["square_outside###sah_foyer", "SQUARE OUTSIDE TO SAH FOYER"],
        ["sah_foyer###sports_centre", "SAH FOYER TO SPORTS CENTRE"],
        ["sah_foyer###square_outside", "SAH FOYER TO SQUARE OUTSIDE"],

        ["library_side###open_side", "LIBRARY SIDE TO OPEN AREA SIDE"],
        ["open_side###library_side", "OPEN AREA SIDE TO LIBRARY SIDE"],

        ["heath_side###far_corridor", "HEATH SIDE TO FAR CORRIDOR"],
        ["heath_side###near_corridor", "HEATH SIDE TO NEAR CORRIDOR"],
        ["far_corridor###near_corridor", "FAR CORRIDOR TO NEAR CORRIDOR"],
        ["far_corridor###heath_side", "FAR CORRIDOR TO HEATH SIDE"],
        ["near_corridor###heath_side", "NEAR CORRIDOR TO HEATH SIDE"],
        ["near_corridor###far_corridor", "NEAR CORRIDOR TO FAR CORRIDOR"],

        ["music###science", "MUSIC TO SCIENCE"],
        ["science###music", "SCIENCE TO MUSIC"],

        ["bbc_science###bbc_science_but_no", "BBC SCIENCE TO B120"],
        ["bbc_science###bbc_va", "BBC_SCIENCE TO BBC VISUAL ARTS"],
        ["bbc_science_but_no###bbc_va", "B120 TO BBC VISUAL ARTS"],
        ["bbc_science_but_no###bbc_science", "B120 TO BBC SCIENCE"],
        ["bbc_va###bbc_science", "BBC VISUAL ARTS TO BBC SCIENCE"],
        ["bbc_va###bbc_science_but_no", "BBC VISUAL ARTS TO B120"],

        ["study_centre###not_library", "BBC STUDY CENTRE TO REGULAR LEVEL 3"],
        ["not_library###study_centre", "REGULAR LEVEL 3 TO BBC STUDY CENTRE"],

        ["junior_school###year_9", "JUNIOR SCHOOL SIDE TO YEAR 9 OPEN AREA SIDE"],
        ["year_9###junior_school", "YEAR 9 OPEN AREA SIDE TO JUNIOR SCHOOL SIDE"],

        ["bbc_foyer_area###far_plaza", "BBC FOYER AREA TO BG19 AREA"],
        ["far_plaza###bbc_foyer_area", "BG19 AREA TO BBC FOYER AREA"]
    ])