//https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

const greetings = ["hello", "hi", "hey", "greetings", "salutations"];

const randomMessages = ["Learning Skills!", 
    "Durham is the best house",
    "Wow, you're on a merit streak!",
    "Check your GPA",
    "<em><br></br></em>",
    "Not Certified by Zscaler!",
    "Also try ChatGPT",
    "Also try ChatGPT",
    "Also try ChatGPT",
    "Also try ChatGPT",
    "Also try ChatGPT",
    "Also try ChatGPT",
    "Also try ChatGPT",
    "salt air"]

const bbcTrigger = ["bbc", "passcode", "password", "code"]

const classrooms = [
    "sg11", "sg12",
    "ms_library",
    "s421", "s423", "s424", "s425", "s426", "s427", "s436","s440", "s438", "s439", "s437",
    "s512", "s538", 
    "s520", "s521", "s522", "s523", "s524",
    "s531", "s532","s533", 
    "s801", "s810", "s815", "s817", 
    "s838", "s839", "s840", "s841", 
    "blg02", "blg03", "blg04", "blg05", "blg06", "blg07", "blg08", 
    "bg18", "bg19", "bg20", 
    "b101", "b102", "b103", "b120", 
    "b125", "b127", "b131", "b130",
    "b201", "b202", "b203", "b204", "b205", "b206", "b207", "b208", "b209",
    "b301", "b302", "b303", "b304", "b305", 
    "b401", "b403", "b404", "b405", "b406", "b407", "b408", "b409", "b410", "b411", "b412", "b413",
    "gym", "fairfax", "gymnasium", "heath", "black_box", "auditorium", "bbca", "health", "ms_office", "it_helpdesk", "cathedral", "chapter", "bbc_reception", "sah_reception"]

const randomText = document.getElementById('random-message');

let messageOfTheDay = Math.floor(Math.random() * randomMessages.length)
console.log(messageOfTheDay)
randomText.textContent = randomMessages[messageOfTheDay]


const levels =  new Map([
    ["sg11",0],["sg12",0],
    ["ms_library",4],
    ["s421",4], ["s423",4], ["s424",4], ["s425",4], ["s426",4], ["s427",4], ["s436",4],["s440",4],["s437",4], ["s438",4], ["s439",4],
    ["s512", 5], ["s538", 5], 
    ["s520", 5], ["s521", 5], ["s522", 5], ["s523", 5], ["s524", 5],
    ["s531", 5], ["s532", 5],["s533", 5], 
    ["s801", 8], ["s810", 8], ["s815", 8], ["s817", 8], 
    ["s838", 8], ["s839", 8], ["s840", 8], ["s841", 8], 
    ["blg02", -1], ["blg03", -1], ["blg04", -1], ["blg05", -1], ["blg06", -1], ["blg07", -1], ["blg08", -1], 
    ["bg18", 0], ["bg19", 0], ["bg20", 0], 
    ["b101", 1], ["b102", 1], ["b103", 1], ["b120", 1], 
    ["b125", 1], ["b127", 1], ["b131", 1], ["b130", 1],
    ["b201", 2], ["b202", 2], ["b203", 2], ["b204", 2], ["b205", 2], ["b206", 2], ["b207", 2], ["b208", 2], ["b209", 2],
    ["b301", 3], ["b302", 3], ["b303", 3], ["b304", 3], ["b305", 3], 
    ["b401", 4], ["b403", 4], ["b404", 4], ["b405", 4], ["b406", 4], ["b407", 4], ["b408", 4], ["b409", 4], ["b410", 4], ["b411", 4], ["b412", 4], ["b413", 4],
    ["gym", 7], ["fairfax", 8], ["gymnasium", 7], ["heath", 5], ["black_box", 0], ["auditorium", 0], ["bbca", 0], ["health",6 ], ["ms_office", 6], ["it_helpdesk", 4], ["cathedral", 0], ["chapter", 0], ["bbc_reception",1], ["sah_reception", 0]])

const building =  new Map([
    ["sg11","SAH"],["sg12","SAH"],
    ["ms_library","SAH"],
    ["s421","SAH"], ["s423","SAH"], ["s424","SAH"], ["s425","SAH"], ["s426","SAH"], ["s427","SAH"], ["s436","SAH"],["s437","SAH"],["s440","SAH"], ["s438","SAH"], ["s439","SAH"],
    ["s512","SAH"], ["s538","SAH"], 
    ["s520","SAH"], ["s521","SAH"], ["s522","SAH"], ["s523","SAH"], ["s524","SAH"], 
    ["s531","SAH"], ["s532","SAH"],["s533","SAH"], 
    ["s801","SAH"], ["s810","SAH"], ["s815","SAH"], ["s817","SAH"], 
    ["s838","SAH"], ["s839","SAH"], ["s840","SAH"], ["s841","SAH"], 
    ["blg02","BBC"], ["blg03","BBC"], ["blg04","BBC"], ["blg05","BBC"], ["blg06","BBC"], ["blg07","BBC"], ["blg08","BBC"], 
    ["bg18","BBC"], ["bg19","BBC"], ["bg20","BBC"], 
    ["b101","BBC"], ["b102","BBC"], ["b103","BBC"], ["b120","BBC"], 
    ["b125","BBC"], ["b127","BBC"], ["b131","BBC"], ["b130","BBC"],
    ["b201","BBC"], ["b202","BBC"], ["b203","BBC"], ["b204","BBC"], ["b205","BBC"], ["b206","BBC"], ["b207","BBC"], ["b208","BBC"], ["b209","BBC"],
    ["b301","BBC"], ["b302","BBC"], ["b303","BBC"], ["b304","BBC"], ["b305","BBC"], 
    ["b401","BBC"], ["b403","BBC"], ["b404","BBC"], ["b405","BBC"], ["b406","BBC"], ["b407","BBC"], ["b408","BBC"], ["b409","BBC"], ["b410","BBC"], ["b411","BBC"], ["b412","BBC"], ["b413","BBC"],
    ["gym", "SAH"], ["fairfax", "SAH"], ["gymnasium", "SAH"], ["heath", "SAH"], ["black_box", "BBC"], ["auditorium", "BBC"], ["bba", "BBC"], ["health","SAH" ], ["ms_office", "SAH"], ["it", "SAH"], ["cathedral", "SAH"], ["chapter", "SAH"], ["bbc_reception", "BBC"], ["sah_reception", "SAH"]])




const from_mid =  new Map([
    ["sg11","walk towards the gym, turn right down the stairs, then turn left"],
    ["sg12","walk towards the gym, turn right down the stairs"],
    ["ms_library","follow signs to Middle School Library"],
    ["s421","follow signs to Middle School Library, then walk into the library, and walk to the left"], 
    ["s423","follow signs to Middle School Library, then turn left before you enter, then turn right and travel to the end of the corridor"], 
    ["s424","follow signs to Middle School Library, then turn left before you enter, then turn right"], 
    ["s425","follow signs to Middle School Library, then turn left before you enter, then turn right"], 
    ["s426","follow signs to Middle School Library, then turn left before you enter"], 
    ["s427","follow signs to the Year 7 Open Area, then turn right as soon as you enter"], 
    ["s436","follow signs to the Year 7 Open Area, then travel forwards and to the right"],
    ["s437","follow signs to the Year 7 Open Area, then turn left after the first corridor"], 
    ["s438","follow signs to the Year 7 Open Area, then turn left after the first corridor"], 
    ["s439","follow signs to the Year 7 Open Area, then turn left after the first corridor"],
    ["s440","follow signs to the Year 7 Open Area, then turn left after the first corridor"],
    ["s512","follow signs to the Heath Centre, then turn left"], 
    ["s538","follow signs to the Heath Centre, then turn right"], 
    ["s520","follow signs to the Year 8 Open Area, then turn right"], 
    ["s521","follow signs to the Year 8 Open Area, then turn right"],
    ["s522","follow signs to the Year 8 Open Area, then continue straight"], 
    ["s523","follow signs to the Year 8 Open Area, then continue straight"], 
    ["s524","follow signs to the Year 8 Open Area, then continue straight"],
    ["s531","follow signs to the Year 8 Open Area, turn left, then turn right at the corridor"], 
    ["s532","follow signs to the Year 8 Open Area, turn left, then turn right at the corridor"],
    ["s533","follow signs to the Year 8 Open Area, turn left, then turn right at the corridor"], 
    ["s801","follow signs to the Fairfax foom, then enter the room through the doors in the far corner"], 
    ["s810","follow signs to the Fairfax room, then the room is on the left"], 
    ["s815","follow signs to the Fairfax room, then turn left down the corridor"], 
    ["s817","follow signs to the Fairfax room, then turn left down the corrdior"], 
    ["s838","follow signs to the science labs, then go straight"], 
    ["s839","follow signs to the science labs, then turn left into the carpeted area"], 
    ["s840","follow signs to the science labs, then turn left into the carpeted area"], 
    ["s841","follow signs to the science labs, then turn left into the carpeted area"], 
    ["blg02","after entering the design centre, go left"], 
    ["blg03","after entering the design centre, go left"], 
    ["blg04","after entering the design centre, go left"], 
    ["blg05","after entering the design centre, go left"], 
    ["blg06","after entering the design centre, go left"], 
    ["blg07","after entering the design centre, the room is on the left"], 
    ["blg08","after entering the design centre, the room is on the right"], 
    ["bg18","travel through the bbc plaza to the far end"], 
    ["bg19","travel through the bbc plaza to the far end, and enter the hallway"], 
    ["bg20","travel through the bbc plaza to the far end, and enter the hallway"], 
    ["b101","turn in to the corridor with the fire doors to the Science centre, and walk down the hallway"], 
    ["b102","turn in to the corridor with the fire doors to the Science centre, and turn to the left"], 
    ["b103","turn in to the corridor with the fire doors to the Science centre, and turn to the left"], 
    ["b120","enter the short corridor opposite the Science centre"], 
    ["b125","walk through to the main open area and B125 is the visible classroom"], 
    ["b127","walk through to the main open area and enter the Visual Arts area"], 
    ["b131","walk through to the main open area and enter the Visual Arts area"], 
    ["b130","walk through to the main open area and enter the Visual Arts area"],
    ["b201","walk through to the main area with the lockers"], 
    ["b202","walk through to the main area with the lockers"],
    ["b203","walk through to the main area with the lockers"], 
    ["b204","walk through to the main area with the lockers"], 
    ["b205","walk through to the main area with the lockers"], 
    ["b206","walk through to the main area with the lockers"], 
    ["b207","walk through to the main area with the lockers"], 
    ["b208","walk through to the main area with the lockers"], 
    ["b209","walk through to the main area with the lockers"],
    ["b301","enter the main area outside of the study centre"], 
    ["b302","enter the main area outside of the study centre"], 
    ["b303","enter the main area outside of the study centre"], 
    ["b304","enter the main area outside of the study centre"], 
    ["b305","enter the study centre and turn right"], 
    ["b401","travel to the end of the open area near the East fire stairs"], 
    ["b403","travel to the end of the open area near the East fire stairs"], 
    ["b404","travel to the end of the open area near the East fire stairs"], 
    ["b405","go to the middle of the main open area"], 
    ["b406","go to the middle of the main open area"], 
    ["b407","go to the middle of the main open area"], 
    ["b408","go to the middle of the main open area"], 
    ["b409","go to the middle of the main open area"], 
    ["b410","go to the middle of the main open area"], 
    ["b411","travel to the end of the open area near the West fire stairs"], 
    ["b412","travel to the end of the open area near the West fire stairs"], 
    ["b413","travel to the end of the open area near the West fire stairs"],
    ["gym", "exit the lift lobby"], 
    ["fairfax", "follow signs to the Fairfax room"], 
    ["gymnasium", "exit the lift lobby"],
    ["heath", "follow signs to the Heath Centre, then turn left, and turn right down the corridor"], 
    ["black_box", "enter the BBC foyer area, then go down the corridor on the right"], 
    ["auditorium", "enter the BBC foyer area, then go down the corridor on the right"], 
    ["bbca", "enter the BBC foyer area, then go down the corridor on the right"], 
    ["health","go towards the Junior School area and travel down the corridor on the right, then turn left" ], 
    ["ms_office", "follow signs to the Year 9 Open Area, then travel across the open area"],  
    ["cathedral", ""], 
    ["chapter", ""], 
    ["bbc_reception", "BBC Reception is located opposite the main staircase on BBC Level 1"],
    ["sah_reception", 'SAH Reception is locatated in the foyer on Ground Floor'],
    ["it_helpdesk", "follow signs to the Middle School Library, then walk straight and to the right, then turn left towards the North Fire Stairs, then travel to level 3"]
    ])


const to_mid =  new Map([
    ["sg11","walk up the stairs to the reception area"],
    ["sg12","walk up the stairs to the reception area"],
    ["ms_library","exit the library through the main entrance"],
    ["s421","exit the library through the main entrance"], 
    ["s423","exit the room into the corridor, and walk back towards the library and the lift lobby"], 
    ["s424","exit the room into the corridor, and walk back towards the library and the lift lobby"], 
    ["s425","exit the room into the corridor, and walk back towards the library and the lift lobby"], 
    ["s426","exit the room into the corridor, and walk back towards the library and the lift lobby"], 
    ["s427","exit the room into Year 7 Open Area, and walk back towards the lift lobby"], 
    ["s436","exit the room into Year 7 Open Area, and walk back towards the lift lobby"],
    ["s437","exit the room into Year 7 Open Area, and walk back towards the lift lobby"],
    ["s440","exit the room into Year 7 Open Area, and walk back towards the lift lobby"], 
    ["s438","exit the room into Year 7 Open Area, and walk back towards the lift lobby"], 
    ["s439","exit the room into Year 7 Open Area, and walk back towards the lift lobby"],
    ["s512","exit the room into the corridor, then walk back towards the lift lobby"], 
    ["s538","exit the room into the corridor, then walk back towards the lift lobby"], 
    ["s520","exit the room into the Year 8 Open Area, then walk back towards the lift lobby"], 
    ["s521","exit the room into the Year 8 Open Area, then walk back towards the lift lobby"],
    ["s522","exit the room into the corridor, then walk back towards the lift lobby"], 
    ["s523","exit the room into the corridor, then walk back towards the lift lobby"], 
    ["s524","exit the room into the corridor, then walk back towards the lift lobby"],
    ["s531","walk through the corridor into the Year 8 Open Area, then walk through to the lift lobby"], 
    ["s532","walk through the corridor into the Year 8 Open Area, then walk through to the lift lobby"],
    ["s533","walk through the corridor into the Year 8 Open Area, then walk through to the lift lobby"], 
    ["s801","walk through the music open area back to the lift lobby"], 
    ["s810","walk through the corridor back to the music open area, then continue through back to the lift lobby"], 
    ["s815","walk through the corridor back to the music open area, then continue through back to the lift lobby"], 
    ["s817","walk through the corridor back to the music open area, then continue through back to the lift lobby"], 
    ["s838","walk through to the science open area, then continue through back to the lift lobby"], 
    ["s839","walk through to the science open area, then continue through back to the lift lobby"], 
    ["s840","walk through to the science open area, then continue through back to the lift lobby"], 
    ["s841","walk through to the science open area, then continue through back to the lift lobby"], 
    ["blg02","walk out of the design centre, then turn towards the dual staircases"], 
    ["blg03","walk out of the design centre, then turn towards the dual staircases"], 
    ["blg04","walk out of the design centre, then turn towards the dual staircases"], 
    ["blg05","walk out of the design centre, then turn towards the dual staircases"], 
    ["blg06","walk out of the design centre, then turn towards the dual staircases"], 
    ["blg07","walk out of the design centre, then turn towards the dual staircases"], 
    ["blg08","walk out of the design centre, then turn towards the dual staircases"], 
    ["bg18","walk through the BBC Plaza back towards the BBC entrance"], 
    ["bg19","walk through the BBC Plaza back towards the BBC entrance"], 
    ["bg20","walk through the BBC Plaza back towards the BBC entrance"], 
    ["b101","walk out of the science area into the main Level 1 corridor"], 
    ["b102","walk out of the science area into the main Level 1 corridor"], 
    ["b103","walk out of the science area into the main Level 1 corridor"], 
    ["b120","exit the classroom, then walk out into the main Level 1 corridor"], 
    ["b125","exit the classroom, then walk out into the main Level 1 corridor"], 
    ["b127","exit the Visual Arts area, then walk out into the main Level 1 corridor"], 
    ["b131","exit the Visual Arts area, then walk out into the main Level 1 corridor"], 
    ["b130","exit the Visual Arts area, then walk out into the main Level 1 corridor"],
    ["b201","exit the classroom, then walk out into the main Level 2 corridor"], 
    ["b202","exit the classroom, then walk out into the main Level 2 corridor"],
    ["b203","exit the classroom, then walk out into the main Level 2 corridor"], 
    ["b204","exit the classroom, then walk out into the main Level 2 corridor"], 
    ["b205","exit the classroom, then walk out into the main Level 2 corridor"], 
    ["b206","exit the classroom, then walk out into the main Level 2 corridor"], 
    ["b207","exit the classroom, then walk out into the main Level 2 corridor"], 
    ["b208","exit the classroom, then walk out into the main Level 2 corridor"], 
    ["b209","exit the classroom, then walk out into the main Level 2 corridor"],
    ["b301","exit the classroom into the open area"], 
    ["b302","exit the classroom into the open area"], 
    ["b303","exit the classroom into the open area"], 
    ["b304","exit the classroom into the open area"], 
    ["b305","exit the classroom into the study centre, then walk out into the open area"], 
    ["b401","exit the classroom into the main Level 4 open area"], 
    ["b403","exit the classroom into the main Level 4 open area"], 
    ["b404","exit the classroom into the main Level 4 open area"], 
    ["b405","exit the classroom into the main Level 4 open area"], 
    ["b406","exit the classroom into the main Level 4 open area"], 
    ["b407","exit the classroom into the main Level 4 open area"], 
    ["b408","exit the classroom into the main Level 4 open area"], 
    ["b409","exit the classroom into the main Level 4 open area"], 
    ["b410","exit the classroom into the main Level 4 open area"], 
    ["b411","exit the classroom into the main Level 4 open area"], 
    ["b412","exit the classroom into the main Level 4 open area"], 
    ["b413","exit the classroom into the main Level 4 open area"],
    ["gym", "exit the gym into the Level 7 lift lobby"], 
    ["fairfax", "walk through the music open area back to the lift lobby"], 
    ["gymnasium", "exit the gym into the Level 7 lift lobby"],
    ["heath", "exit into the corridor, then walk back towards the lift lobby"], 
    ["black_box", "exit into the corridor, then walk back towards the foyer area"], 
    ["auditorium", "exit into the corridor, then walk back towards the foyer area"], 
    ["bbca", "exit into the corridor, then walk back towards the foyer area"], 
    ["health","exit into the corridor, then turn to the right and walk back towards the lift lobby" ], 
    ["ms_office", "exit into the Year 9 Open Area, then walk back towards the lift lobby"],  
    ["cathedral", ""], 
    ["chapter", ""], 
    ["bbc_reception", ""],
     ["sah_reception", '']
    ])



    const sub_area =  new Map([
    ["sg11","sports_centre"], ["sg12","sports_centre"],
    ["ms_library","library_side"],
    ["s421","library_side"], ["s423","library_side"], ["s424","library_side"], ["s425","library_side"], ["s426","library_side"], ["s427","open_side"], ["s436","open_side"],["s437","open_side"],["s440","open_side"], ["s438","open_side"], ["s439","open_side"],
    ["s512","heath_side"], ["s538","heath_side"], 
    ["s520","near_corridor"], ["s521","near_corridor"], ["s522","near_corridor"], ["s523","near_corridor"], ["s524","near_corridor"], 
    ["s531","far_corridor"], ["s532","far_corridor"],["s533","far_corridor"], 
    ["s801","music"], ["s810","music"], ["s815","music"], ["s817","music"], 
    ["s838","science"], ["s839","science"], ["s840","science"], ["s841","science"], 
    ["blg02","design"], ["blg03","design"], ["blg04","design"], ["blg05","design"], ["blg06","design"], ["blg07","design"], ["blg08","design"], 
    ["bg18","far_plaza"], ["bg19","far_plaza"], ["bg20","far_plaza"], 
    ["b101","bbc_science"], ["b102","bbc_science"], ["b103","bbc_science"], ["b120","bbc_science_but_no"], 
    ["b125","bbc_va"], ["b127","bbc_va"], ["b131","bbc_va"], ["b130","bbc_va"],
    ["b201","level_two"], ["b202","level_two"], ["b203","level_two"], ["b204","level_two"], ["b205","level_two"], ["b206","level_two"], ["b207","level_two"], ["b208","level_two"], ["b209","level_two"],
    ["b301","not_library"], ["b302","not_library"], ["b303","not_library"], ["b304","not_library"], ["b305","not_library"], 
    ["b401","bbc_level_four"], ["b403","bbc_level_four"], ["b404","bbc_level_four"], ["b405","bbc_level_four"], ["b406","bbc_level_four"], ["b407","bbc_level_four"], ["b408","bbc_level_four"], ["b409","bbc_level_four"], ["b410","bbc_level_four"], ["b411","bbc_level_four"], ["b412","bbc_level_four"], ["b413","bbc_level_four"],
    ["gym", "level_7"], ["fairfax", "music"], ["gymnasium", "level_7"], ["heath", "heath_side"], ["black_box", "bbc_foyer_area"], ["auditorium", "bbc_foyer_area"], ["bbca", "bbc_foyer_area"], ["health","junior_school" ], ["ms_office", "year_9"], ["cathedral", "square_outside"], ["chapter", "square_outside"], ["bbc_reception", "bbc_foyer_area"], ["sah_reception", "sah_foyer"]])



    const sub_directions = new Map([
        ["sports_centre###square_outside", "SPORTS CENTRE TO SQUARE OUTSIDE"],
        ["sports_centre###sah_foyer", "SPORTS CENTRE TO SAH FOYER"],
        ["square_outside###sports_centre", "SQUARE OUTSIDE TO SPORTS CENTRE"],
        ["square_outside###sah_foyer", "SQUARE OUTSIDE TO SAH FOYER"],
        ["sah_foyer###sports_centre", "SAH FOYER TO SPORTS CENTRE"],
        ["sah_foyer###square_outside", "SAH FOYER TO SQUARE OUTSIDE"],

        ["library_side###open_side", "LIBRARY SIDE TO OPEN AREA SIDE"],
        ["open_side###library_side", "OPEN AREA SIDE TO LIBRARY SIDE"],

        ["heath_side###far_corridor", "HEATH SIDE TO FAR CORRIDOR"],
        ["heath_side###near_corridor", "HEATH SIDE TO NEAR CORRIDOR"],
        ["far_corridor###near_corridor", "FAR CORRIDOR TO NEAR CORRIDOR"],
        ["far_corridor###heath_side", "FAR CORRIDOR TO HEATH SIDE"],
        ["near_corridor###heath_side", "NEAR CORRIDOR TO HEATH SIDE"],
        ["near_corridor###far_corridor", "NEAR CORRIDOR TO FAR CORRIDOR"],

        ["music###science", "MUSIC TO SCIENCE"],
        ["science###music", "SCIENCE TO MUSIC"],

        ["bbc_science###bbc_science_but_no", "BBC SCIENCE TO B120"],
        ["bbc_science###bbc_va", "BBC_SCIENCE TO BBC VISUAL ARTS"],
        ["bbc_science_but_no###bbc_va", "B120 TO BBC VISUAL ARTS"],
        ["bbc_science_but_no###bbc_science", "B120 TO BBC SCIENCE"],
        ["bbc_va###bbc_science", "BBC VISUAL ARTS TO BBC SCIENCE"],
        ["bbc_va###bbc_science_but_no", "BBC VISUAL ARTS TO B120"],

        ["study_centre###not_library", "BBC STUDY CENTRE TO REGULAR LEVEL 3"],
        ["not_library###study_centre", "REGULAR LEVEL 3 TO BBC STUDY CENTRE"],

        ["junior_school###year_9", "JUNIOR SCHOOL SIDE TO YEAR 9 OPEN AREA SIDE"],
        ["year_9###junior_school", "YEAR 9 OPEN AREA SIDE TO JUNIOR SCHOOL SIDE"],

        ["bbc_foyer_area###far_plaza", "BBC FOYER AREA TO BG19 AREA"],
        ["far_plaza###bbc_foyer_area", "BG19 AREA TO BBC FOYER AREA"]
    ])